name: 'health_insights'
version: '1.0'
config-version: 2
profile: 'health_insights'

model-paths: [ 'models' ]

vars:
  analysis_start: '2022-01-01'
  analysis_end: '2023-12-31'

models:
  health_insights:
    +materialized: view
    staging:
      +schema: raw_stg
    intermediate:
      +schema: silver
    marts:
      +schema: marts
      +materialized: table

seeds:
  +database: HEALTH_INSIGHTS
  +schema: RAW_STG
  +quote_columns: false
