name: 'health_insights'
version: '1.0'
config-version: 2
profile: 'health_insights'

model-paths: [ 'models' ]
seed-paths: [ 'seeds' ]
macro-paths: [ 'macros' ]

vars:
  analysis_start: '2022-01-01'
  analysis_end: '2023-12-31'
  has_maternal_fields: true

flags:
  use_materialization_v2: true

models:
  health_insights:
    +materialized: view

    staging:
      +schema: raw_stg

    intermediate:
      +schema: silver

    marts:
      +schema: marts
      +materialized: table # default para tudo em marts

      dim:
        +materialized: table # dims como tabela

      facts:
        +materialized: incremental
        +unique_key: sk_birth
        +incremental_strategy: merge
        +on_schema_change: sync_all_columns

    databricks:
      +enabled: "{{ target.type in ['databricks','spark'] or target.name == 'prod' }}"

seeds:
  health_insights:
    +database: "{{ 'HEALTH_INSIGHTS' if target.type == 'snowflake' else (target.catalog or 'health_insights') }}"
    +schema: >
      {% if target.type == 'snowflake' %}RAW_STG{% else %}raw_stg_marts{% endif %}
    +quote_columns: false
